# Dockerfile used for creating a container capable to run AcmeAir monolithic
# Must be running on the same network as the mongodb container
# mongo.properties file must contain the machine where mongo is going to be run
FROM websphere-liberty:webProfile7
USER root

# Copy the JITaaS SDK
#COPY j2sdk-image-openj9 /opt/ibm/java1

COPY --chown=1001:0 LibertyFiles/server.xml /config/server.xml
COPY --chown=1001:0 LibertyFiles/mongo.properties /config/mongo.properties
COPY --chown=1001:0 LibertyFiles/acmeair-webapp-2.0.0-SNAPSHOT.war /config/apps
ENV ACMEAIR_PROPERTIES=/config/mongo.properties


#ENV JAVA_HOME="/opt/ibm/java1"

RUN configure.sh
